#obj-m+=suzanne_tim.o
 
#all:
# make -C /lib/modules/$(shell uname -r)/build/ M=$(PWD) modules
# $(CC) suzanne_tim_test.c -o test
#clean:
# make -C /lib/modules/$(shell uname -r)/build/ M=$(PWD) clean
# rm test


# To run execute the following:
#  make -C /lib/modules/$(uname -r)/build M=$(pwd) modules
#  insmod suzanne_tim.ko
# Also see https://raspberrypi.stackexchange.com/questions/39845/how-compile-a-loadable-kernel-module-without-recompiling-kernel
obj-m := suzanne_tim.o